# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: legal.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'legal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blegal.proto\x12\x0bliceu.legal\"\xf8\x01\n\nLegalEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x13\n\x0b\x65ntity_type\x18\x03 \x01(\t\x12\x11\n\tentity_id\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\t\x12\x0e\n\x06module\x18\x06 \x01(\t\x12\x37\n\x08metadata\x18\x07 \x03(\x0b\x32%.liceu.legal.LegalEvent.MetadataEntry\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8e\x01\n\x08\x43ontract\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65\x61l_id\x18\x02 \x01(\t\x12\x13\n\x0bproperty_id\x18\x03 \x01(\t\x12\x0f\n\x07parties\x18\x04 \x03(\t\x12\r\n\x05value\x18\x05 \x01(\x01\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x0c\n\x04hash\x18\x07 \x01(\t\x12\x12\n\ncreated_at\x18\x08 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'legal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEGALEVENT_METADATAENTRY']._loaded_options = None
  _globals['_LEGALEVENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_LEGALEVENT']._serialized_start=29
  _globals['_LEGALEVENT']._serialized_end=277
  _globals['_LEGALEVENT_METADATAENTRY']._serialized_start=230
  _globals['_LEGALEVENT_METADATAENTRY']._serialized_end=277
  _globals['_CONTRACT']._serialized_start=280
  _globals['_CONTRACT']._serialized_end=422
# @@protoc_insertion_point(module_scope)
