LEGAL_SUBJECTS = [
    "legal.contract.created",
    "legal.contract.signed",
    "legal.contract.breach",
    "legal.arbitration.started",
    "legal.arbitration.closed",
    "legal.compliance.alert",
    "legal.audit.created",
    "legal.pericia.generated",
    "legal.embargo.detected",
    "legal.asset.risk",
    "legal.sst.violation",
    "legal.esg.alert",
    "legal.tax.risk",
    "legal.governance.blocked",
]
